#from . import invoice_service
from . import partner_service
#from . import product_service
#from . import partner_service_test
#from . import city_service
#from . import country_service
#from . import purchase_service
#from . import product
#from . import mrp_workcenter_productivity_loss
#from . import product_tracking_service
#from . import stock_production_service
#from . import workorder_service
#from . import lot_update_service
#from . import workorder_users
#from . import workcenter_service
#from . import workcenter_loss_service
